# Generated by Django 5.1.5 on 2025-02-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='上传的图片文件', max_length=500, upload_to='photos/'),
        ),
    ]
